---
- name: ping to gocd server

  hosts:
    - gocd_server

  become: yes

  tasks:
    - name: copy {{ pkg_go_server }}
      copy: src={{ pkg_go_server }} dest=/tmp/{{ pkg_go_server }}

    - name: install {{ pkg_go_server }}
      apt: deb=/tmp/{{ pkg_go_server }}

